services:
    postgres:
        image: postgres:15
        container_name: evlisting-db
        restart: always
        environment:
            POSTGRES_USER: rihan
            POSTGRES_PASSWORD: edrihan
            POSTGRES_DB: evlistingdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
