app = "your-app-name"

# Set the kill signal and timeout for graceful shutdowns
kill_signal = "SIGINT"
kill_timeout = 5

# Environment variables
[env]
  PORT = "3005"
  DATABASE_URL = "postgresql://neondb_owner:npg_YfeoJ6X9xuvl@ep-floral-unit-a2pyb06c-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require"

# Build configuration using Heroku's buildpacks
[build]
  builder = "heroku/buildpacks:20"
  [build.env]
    NODE_ENV = "production"

# Deployment configuration
[deploy]
  release_command = "npx prisma migrate deploy"

# Define the services
[[services]]
  internal_port = 3005
  protocol = "tcp"

  # HTTP port
  [[services.ports]]
    port = 80
    handlers = ["http"]

  # HTTPS port
    [[services.ports]]
      port = 443
      handlers = ["tls", "http"]

  # Health checks
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 6 